import faker from 'faker';

faker.seed(69);

class User {
    constructor(
        public name: string,
        public location: string,
        public languages: string[],
        public bio: string,
        public since: Date,
        public avatar: string
    ) {}
}

const userCount = 250;
export const users: User[] = [];

const languages = [
    "Afar",
    "Afrikaans",
    "Aja-Gbe",
    "Akan",
    "Albanian",
    "Amharic",
    "Anii",
    "Arabic",
    "Armenian",
    "Assamese",
    "Aymara",
    "Azerbaijani",
    "Balanta",
    "Bambara",
    "Bariba",
    "Basque",
    "Bassari",
    "Bedik",
    "Belarusian",
    "Bengali",
    "Berber",
    "Biali",
    "Bislama",
    "Boko",
    "Bomu",
    "Bosnian",
    "Bozo",
    "Buduma",
    "Bulgarian",
    "Burmese",
    "Cantonese",
    "Catalan",
    "Chinese, Mandarin",
    "Chichewa",
    "Chirbawe",
    "Comorian",
    "Croatian",
    "Czech",
    "Dagaare",
    "Dagbani",
    "Dangme",
    "Danish",
    "Dari",
    "Dendi",
    "Dhivehi",
    "Dioula",
    "Dogon",
    "Dutch",
    "Dzongkha",
    "English",
    "Estonian",
    "Ewe-Gbe",
    "Fijian",
    "Filipino",
    "Finnish",
    "Fon-Gbe",
    "Foodo",
    "Formosan",
    "French",
    "Fula",
    "Ga",
    "Gàidhlig",
    "Gbe",
    "Gen-Gbe",
    "Georgian",
    "German",
    "Gonja",
    "Gourmanché",
    "Greek",
    "Guaraní",
    "Gujarati",
    "Haitian Creole",
    "Hakka",
    "Hassaniya",
    "Hausa",
    "Hebrew",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Igbo",
    "Icelandic",
    "Indonesian",
    "Irish",
    "Italian",
    "Japanese",
    "Jola",
    "Kabye",
    "Kalanga",
    "Kannada",
    "Kanuri",
    "Kasem",
    "Kazakh",
    "Khmer",
    "Kinyarwanda",
    "Kirundi",
    "Kissi",
    "Khoisan",
    "Korean",
    "Korean Sign Language",
    "Kpelle",
    "Kurdish",
    "Kyrgyz",
    "Lao",
    "Latvian",
    "Lithuanian",
    "Lukpa",
    "Luxembourgish",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malinke",
    "Maltese",
    "Mamara",
    "Manding",
    "Mandinka",
    "Malinke",
    "Mandinka",
    "Mandjak",
    "Mankanya",
    "Manx Gaelic",
    "Māori",
    "Marshallese",
    "Mbelime",
    "Moldovan",
    "Mongolian",
    "Montenegrin",
    "Mossi",
    "Nambya",
    "Nateni",
    "Nauruan",
    "Ndau",
    "Nepali",
    "New Zealand Sign Language",
    "Noon",
    "North Korean",
    "Northern Sotho",
    "Norwegian",
    "Nzema",
    "Oniyan",
    "Ossetian",
    "Palauan",
    "Papiamento",
    "Pashto",
    "Persian",
    "Polish",
    "Portuguese",
    "Punjabi",
    "Quechua",
    "Romanian",
    "Romansh",
    "Russian",
    "Safen",
    "Samoa",
    "Sango",
    "Sena",
    "Serbian",
    "Serer",
    "Seychellois Creole",
    "Shona",
    "Sinhala",
    "Slovak",
    "Slovene",
    "Somali",
    "Songhay",
    "Zarma",
    "Soninke",
    "Sotho",
    "Spanish",
    "Susu",
    "Swahili",
    "Swati",
    "Swedish",
    "Syenara",
    "Tajik",
    "Tagalog",
    "Tamasheq",
    "Tamil",
    "Tammari",
    "Tasawaq",
    "Tebu",
    "Telugu",
    "Tetum",
    "Thai",
    "Tigrinya",
    "Tok Pisin",
    "Toma",
    "Tonga",
    "Tongan",
    "Tsonga",
    "Tswana",
    "Turkish",
    "Turkmen",
    "Tuvaluan",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Venda",
    "Vietnamese",
    "Waama",
    "Waci-Gbe",
    "Wamey",
    "Welsh",
    "Wolof",
    "Xhosa",
    "Xwela-Gbe",
    "Yobe",
    "Yom",
    "Yoruba",
    "Zimbabwean sign language",
    "Zulu",
    "Abaza",
    "Adyghe",
    "Aghul",
    "Aklanon",
    "Albanian",
    "Altay",
    "Arabic",
    "Armenian",
    "Assamese",
    "Avar",
    "Azeri",
    "Balkar",
    "Bashkir",
    "Basque",
    "Bengali",
    "Bikol",
    "Bosnian",
    "Buryat",
    "Cantonese Chinese",
    "Catalan",
    "Cebuano",
    "Chavacano",
    "Chechen",
    "Cherkess",
    "Cherokee",
    "Chipewyan",
    "Chukchi",
    "Chuvash",
    "Cree",
    "Crimean Tatar",
    "Croatian",
    "Dargwa",
    "Dolgan",
    "Dutch",
    "Erzya",
    "Even",
    "Evenki",
    "Faroese",
    "Finnish",
    "French",
    "Frisian (West)",
    "Gagauz",
    "Galician",
    "German",
    "Greek",
    "Guaraní",
    "Gujarati",
    "Gwich'in",
    "Hawaiian",
    "Hiligaynon",
    "Hindi",
    "Hungarian",
    "Ibanag",
    "Ilocano",
    "Ingush",
    "Inuinnaqtun",
    "Inuktitut",
    "Inuvialuktun",
    "Irish",
    "Italian",
    "Ivatan",
    "Japanese",
    "Kabardian",
    "Kalaallisut",
    "Kalmyk",
    "Kannada",
    "Kapampangan",
    "Karachay",
    "Karelian",
    "Kashmiri",
    "Kazakh",
    "Khakas",
    "Khanty",
    "Kinaray-a",
    "Komi",
    "Komi-Permyak",
    "Korean",
    "Kumyk",
    "Kyrgyz",
    "Lak",
    "Lezgian",
    "Macedonian",
    "Maguindanao",
    "Malayalam",
    "Mansi",
    "Maranao",
    "Marathi",
    "Mari",
    "Mayan",
    "Moksha",
    "Mongolian",
    "Náhuatl",
    "Nenets",
    "Nepali",
    "Nogai",
    "Occitan",
    "Odia",
    "Ossetic",
    "Pangasinan",
    "Portuguese",
    "Punjabi",
    "Romanian",
    "Russian",
    "Rusyn",
    "Rutul",
    "Sakha",
    "Sambal",
    "Sami",
    "Sanskrit",
    "Saraiki",
    "Sarikoli",
    "Scottish Gaelic",
    "Scots",
    "Selkup",
    "Serbian",
    "Sindhi",
    "North and South Slavey",
    "Slovak",
    "Slovene",
    "Spanish",
    "Surigaonon",
    "Tabasaran",
    "Tagalog",
    "Tahitian",
    "Tamil",
    "Tat",
    "Tatar",
    "Tausug",
    "Telugu",
    "Tibetan",
    "Tłįchǫ",
    "Tsakhur",
    "Tswana",
    "Turkish",
    "Tuvan",
    "Udmurt",
    "Urdu",
    "Uyghur",
    "Veps",
    "Vietnamese",
    "Waray",
    "Welsh",
    "Yakan",
    "Yiddish",
    "Yukaghir",
    "Zhuang"
  ];
  
for (let i = 0; i < userCount; i++) {
    users.push(new User(
        faker.name.firstName(),
        faker.fake("{{location.city}}, {{location.country}}"),
        [faker.random.arrayElement(languages), faker.random.arrayElement(languages)],
        faker.lorem.sentences(2),
        faker.date.recent(120),
        faker.image.avatar()
    ));
}

export function findUsers(location: string, language: string) {
    return users.filter(user => user.location.includes(location) && user.languages.indexOf(language) != -1)
}